### ISSUE TITLE
Institution Profile page does not load

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#208]
Began receiving an error when trying to access the Institution Profile page
![screen shot 2017-05-11 at 2 37 23 pm](https://cloud.githubusercontent.com/assets/1204467/25973091/89a58782-3657-11e7-8a79-d5114d9de3e5.png)

Logs report the following error:
```shell
I, [2017-05-11T14:13:34.680426 #2548]  INFO -- : Started GET "/institutions" for 128.48.204.203 at 2017-05-11 14:13:34 -0700
I, [2017-05-11T14:13:34.682215 #2548]  INFO -- : Processing by InstitutionsController#index as HTML
I, [2017-05-11T14:13:35.174551 #2548]  INFO -- : Completed 404 Not Found in 492ms
F, [2017-05-11T14:13:35.176085 #2548] FATAL -- : 
ActiveRecord::RecordNotFound (Couldn't find RequirementsTemplate with id=266):
  app/controllers/institutions_controller.rb:96:in `block in institutional_statistics'
  app/controllers/institutions_controller.rb:95:in `institutional_statistics'
  app/controllers/institutions_controller.rb:55:in `index'
  /appsunicorn (5.1.0) lib/unicorn/http_server.rb:562:in `process_client'
  /appsunicorn (5.1.0) lib/unicorn/http_server.rb:658:in `worker_loop'
  /appsunicorn (5.1.0) lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
  /appsunicorn (5.1.0) lib/unicorn/http_server.rb:132:in `start'
```

The template in question must have been deleted and for some reason ActiveRecord's `Model.find()` throws an exception rather than just returning a nil value. Switched to `Model.find_by(id: '')` which will return a nil that we can check for before proceeding.

**Comment by briri** [comment]
fixed by https://github.com/CDLUC3/dmptool/commit/3849b6a37ad1befcda00c45c884357cf24d03f35
