### ISSUE TITLE
Unexpected Application Error! received when trying to upload plan

### ISSUE THREAD

**Issue by magicalmary** [CDLUC3/dmptool#562]
Administrator user:  Katherine E. Koziar, University of California, Riverside

 User reported the following error message via email, but is not currently available to clarify the steps in order to recreate it:

"I can access the upload feature, and tried uploading, but received this error message (see below)... Fyi, I continue to receive the error when I click on “Upload Plan.” When I uploaded the DMP originally, I filled out all prompted fields except research outputs."

**Unexpected Application Error!**

Cannot read properties of null (reading '1')

TypeError: Cannot read properties of null (reading '1')

    at https://dmptool.org/assets/reactApplication-3d56908fe58519d9f7385e84b4256c12baab99bfb5b5602065ec4bb76978e98c.js:2:524271

    at Array.map (<anonymous>)

    at fr (https://dmptool.org/assets/reactApplication-3d56908fe58519d9f7385e84b4256c12baab99bfb5b5602065ec4bb76978e98c.js:2:524205)

    at ko (https://dmptool.org/assets/reactApplication-3d56908fe58519d9f7385e84b4256c12baab99bfb5b5602065ec4bb76978e98c.js:2:355344)

    at Ss (https://dmptool.org/assets/reactApplication-3d56908fe58519d9f7385e84b4256c12baab99bfb5b5602065ec4bb76978e98c.js:2:366925)

    at kl (https://dmptool.org/assets/reactApplication-3d56908fe58519d9f7385e84b4256c12baab99bfb5b5602065ec4bb76978e98c.js:2:412695)

    at bu (https://dmptool.org/assets/reactApplication-3d56908fe58519d9f7385e84b4256c12baab99bfb5b5602065ec4bb76978e98c.js:2:401080)

    at gu (https://dmptool.org/assets/reactApplication-3d56908fe58519d9f7385e84b4256c12baab99bfb5b5602065ec4bb76978e98c.js:2:401008)

    at yu (https://dmptool.org/assets/reactApplication-3d56908fe58519d9f7385e84b4256c12baab99bfb5b5602065ec4bb76978e98c.js:2:400871)

    at ou (https://dmptool.org/assets/reactApplication-3d56908fe58519d9f7385e84b4256c12baab99bfb5b5602065ec4bb76978e98c.js:2:397706)

**Comment by magicalmary** [comment]
user's email:  katherine.koziar@ucr.edu

**Comment by magicalmary** [comment]
I've have tried to replicate this on staging and production, but am unable.

**Comment by briri** [comment]
Did some initial investigation of the logs. We do not see any PUT/POST requests which indicates that the error is happening on the client side.

We are curious as to what browser she might be using and if she has any plugins.
