### ISSUE TITLE
Condition Logic broken in upgraded Rails 7.2 system

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#666]
Experiencing multiple issues dealing with templates that use conditional logic (and plans based off of them).

Template sections cannot be expanded if they contain a question with conditional logic: 
```
dmptool-1  | 00:32:25 web.1          | ActionView::Template::Error (You tried to define an enum named "action_type" on the model "Condition", but this will generate a instance method "remove?", which is already defined by another enum.):
dmptool-1  | 00:32:25 web.1          | 
dmptool-1  | 00:32:25 web.1          | Causes:
dmptool-1  | 00:32:25 web.1          | ArgumentError (You tried to define an enum named "action_type" on the model "Condition", but this will generate a instance method "remove?", which is already defined by another enum.)
dmptool-1  | 00:32:25 web.1          |     3:   <%= render partial: "org_admin/questions/show",
dmptool-1  | 00:32:25 web.1          |     4:     locals: local_assigns.merge({
dmptool-1  | 00:32:25 web.1          |     5:       question: question,
dmptool-1  | 00:32:25 web.1          |     6:       conditions: question.conditions.order(:number)
dmptool-1  | 00:32:25 web.1          |     7:     }) %>
dmptool-1  | 00:32:25 web.1          |     8: </div>
dmptool-1  | 00:32:25 web.1          |   
dmptool-1  | 00:32:25 web.1          | app/models/condition.rb:29:in `<class:Condition>'
```

Cannot add new conditional logic. The logs report:
```
dmptool-1  | 00:37:16 web.1          | NoMethodError (undefined method `each' for nil:NilClass):
dmptool-1  | 00:37:16 web.1          |   
dmptool-1  | 00:37:16 web.1          | app/controllers/org_admin/questions_controller.rb:236:in `sanitize_hash'
dmptool-1  | 00:37:16 web.1          | app/controllers/org_admin/questions_controller.rb:169:in `update'
```

Which is due to the way the parameters are passed into the controller. They do not use the Rails standard `_attributes` suffix but instead use a custom approach that involves the `app/helpers/condition_helper.rb`

The data is also serialized as `TEXT` delimited by newline characters when it should really be stored as JSON arrays.

**Comment by briri** [comment]
I was able to get things working with a small amount of changes. There are some caveats though.

Needed to update underlying data within the table so that they are JSON arrays using the following query:
```
UPDATE conditions
SET option_list = CONCAT(CONCAT('[', REPLACE(REPLACE(REPLACE(option_list, '---\n- \'', '"'), '\'\n- \'', '","'), '\'\n', '"')), ']'),
  remove_data = CONCAT(CONCAT('[', REPLACE(REPLACE(REPLACE(remove_data, '---\n- \'', '"'), '\'\n- \'', '","'), '\'\n', '"')), ']')
where option_list like '---%';
```

Updated the form partials in `app/views/org_admin/conditions` to properly send condition data to the controller. 

Made the following changes to simplify this patch and to make it a little more user friendly. 
- Conditions can be added or removed (not updated anymore)
- Hovering over the email of an existing condition displays a tooltip that shows the email message, subject, etc. (not fully accessible, but then again the original was not either)
- The "Add Conditions" button will now say "Edit Conditions" if there are any.
- Updated the column heading over the "thing that happens when the condition is met" from "Remove" to "Target" since the content of the column can either be questions being removed or an email notification being sent.
